base/urls.py
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('list/',
         views.JobListView.as_view(), name='list'),
    path('publish/',
         views.JobPublishView.as_view(), name='publish'),
    path('update/<int:pk>/',
         views.JobUpdateView.as_view(), name='update'),
    path('search/',
         views.JobListViewSearch.as_view(), name='search'),
    path('j/<int:pk>/',
         views.JobDetailView.as_view(), name='job'),
    path('a/<int:pk>/',
         views.JobApplyView.as_view(), name='apply'),
    path('applicants/<int:pk>/',
         views.JobApplicantsView.as_view(), name='applicants'),
]

users/urls.py
from django.urls import path

from users import views

app_name = 'users'

urlpatterns = [
    path('login/',
         views.LoginView.as_view(), name='login'),
    path('logincreate/',
         views.LoginCreateView.as_view(), name='login_create'),
    path('u/register/',
         views.ApplicantRegisterView.as_view(), name='u_register'),
    path('u/create/',
         views.ApplicantCreateView.as_view(), name='u_create'),
    path('u/dashboard/',
         views.ApplicantDashboardView.as_view(), name='u_dashboard'),
    path('c/register/',
         views.CompanyRegisterView.as_view(), name='c_register'),
    path('c/create/',
         views.CompanyCreateView.as_view(), name='c_create'),
    path('c/dashboard/',
         views.CompanyDashboardView.as_view(), name='c_dashboard'),
    path('c/delete/', views.DashboardJobDelete.as_view(),
         name='job_delete'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('c/charts/',
         views.CompanyChartsView.as_view(), name='charts'),
]

users/models.py
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models
from django.forms import ValidationError
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValidationError(_('The email field cannot be empty'))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    phone_number = models.IntegerField(blank=True, null=True)
    is_company = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    objects = CustomUserManager()
    USERNAME_FIELD = 'email'

    def __str__(self):
        return self.email


class ApplicantProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    title = models.CharField(max_length=60)
    years_experience = models.IntegerField(default=0)
    experience = models.TextField()
    education = models.TextField()
    skills = models.TextField()

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class CompanyProfile(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    description = models.TextField()
    website = models.URLField()

users/forms/login_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

from utils.django_forms import add_placeholder


class LoginForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        add_placeholder(self.fields['email'], _('Enter your email'))
        add_placeholder(self.fields['password'], _('Enter your password'))

    email = forms.CharField(label=_('Email *'))
    password = forms.CharField(
        widget=forms.PasswordInput(), label=_('Password *'))

users/views/applicant_dashboard.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import View

from jobs.models import Application


class ApplicantDashboardView(LoginRequiredMixin, View):
    login_url = 'users:login'
    template_name = 'users/pages/applicant_dashboard.html'
    redirect_field_name = 'next'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and request.user.is_company:
            return redirect('users:c_dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        applications = Application.objects.select_related(
            'applicant_profile'
        ).filter(
            applicant_profile=request.user.applicantprofile
        ).order_by('-id')
        context = {
            'applications': applications,
        }
        return render(request, self.template_name, context=context)

users/views/applicant_register.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View

from users.forms import ApplicantRegisterForm
from users.models import ApplicantProfile


class ApplicantRegisterView(View):
    template_name = 'users/pages/applicant_register.html'

    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, _('You cannot register while logged in'))
            return redirect(reverse('users:u_dashboard'))
        form_data = request.session.pop('register_form_data', None)
        form = ApplicantRegisterForm(form_data)
        context = {
            'form': form,
            'form_action': reverse('users:u_create'),
        }
        return render(
            request, self.template_name, context=context
        )


class ApplicantCreateView(View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        POST = request.POST
        request.session['register_form_data'] = POST
        form = ApplicantRegisterForm(POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.save()
            ApplicantProfile.objects.create(
                user=user,
                first_name=form.cleaned_data.get('first_name', ''),
                last_name=form.cleaned_data.get('last_name', ''),
                title=form.cleaned_data.get('title', ''),
                years_experience=form.cleaned_data.get('years_experience', 0),
                experience=form.cleaned_data.get('experience', ''),
                education=form.cleaned_data.get('education', ''),
                skills=form.cleaned_data.get('skills', ''),
            )
            user_created = _(
                'User has been created, please log in'
            )
            messages.success(request, user_created)
            del request.session['register_form_data']
            return redirect(reverse('users:login'))
        return redirect('users:u_register')

users/views/company_charts.py
import json
from datetime import datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.serializers.json import DjangoJSONEncoder
from django.db.models import Count
from django.http import Http404
from django.shortcuts import render
from django.views.generic import View

from jobs.models import Application, Job


class CompanyChartsView(LoginRequiredMixin, View):
    template_name = 'users/pages/company_charts.html'
    context_object_name = 'company'

    def get_queryset(self):
        company_profile = self.request.user.companyprofile

        today = datetime.now().date()
        start_date = today - timedelta(days=29)

        job_queryset = Job.objects.filter(
            company_profile=company_profile,
            created_date__date__range=(start_date, today)
        ).values('created_date__date').annotate(
            count=Count('id')
        ).order_by('created_date__date')

        application_queryset = Application.objects.filter(
            job__company_profile=company_profile,
            applied_date__date__range=(start_date, today)
        ).values('applied_date__date').annotate(
            count=Count('id')
        ).order_by('applied_date__date')

        queryset1 = [
            {'created_date__date': item['created_date__date'],
             'count': item['count']}
            for item in job_queryset
        ]

        queryset2 = [
            {'applied_date__date': item['applied_date__date'],
             'count': item['count']}
            for item in application_queryset
        ]

        return queryset1, queryset2

    def get(self, request):
        if not request.user.is_company:
            raise Http404()

        queryset1, queryset2 = self.get_queryset()
        chart_data1 = json.dumps(queryset1, cls=DjangoJSONEncoder)
        chart_data2 = json.dumps(queryset2, cls=DjangoJSONEncoder)
        context = {
            'chart_data1': chart_data1,
            'chart_data2': chart_data2,
        }
        return render(request, self.template_name, context=context)

users/views/company_dashboard.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext_lazy as _
from django.views import View

from jobs.models import Job


class CompanyDashboardView(LoginRequiredMixin, View):
    login_url = 'users:login'
    template_name = 'users/pages/company_dashboard.html'
    redirect_field_name = 'next'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.is_company:
            return redirect('users:u_dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get_queryset(self):
        queryset = Job.objects.filter(
            company_profile=self.request.user.companyprofile)
        queryset = queryset.select_related('company_profile')
        queryset = queryset.annotate(application_count=Count('applications'))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def get_job(self, id=None):
        job = None
        if not self.request.user.is_company:
            raise Http404()
        if id:
            job = Job.objects.filter(
                company_profile=self.request.user.companyprofile,
                id=id,
            ).first()
            if not job:
                raise Http404()
        return job

    def get(self, request):
        jobs = self.get_queryset().order_by('-id')
        context = {
            'jobs': jobs,
        }
        return render(request, self.template_name, context=context)


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class DashboardJobDelete(CompanyDashboardView):
    def post(self, *args, **kwargs):
        job = self.get_job(self.request.POST.get('id'))
        if not job:
            messages.warning(self.request, _('Job post not found'))
        else:
            job.delete()
            messages.success(self.request, _('Job post successfully deleted'))
        return redirect(reverse('users:c_dashboard'))

users/views/company_register.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View

from users.forms import CompanyRegisterForm
from users.models import CompanyProfile


class CompanyRegisterView(View):
    template_name = 'users/pages/company_register.html'

    def get(self, request):
        if request.user.is_authenticated:
            messages.warning(request, _('You cannot register while logged in'))
            return redirect(reverse('users:c_dashboard'))
        form_data = request.session.pop('register_form_data', None)
        form = CompanyRegisterForm(form_data)
        context = {
            'form': form,
            'form_action': reverse('users:c_create'),
        }
        return render(
            request, self.template_name, context=context
        )


class CompanyCreateView(View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        POST = request.POST
        request.session['register_form_data'] = POST
        form = CompanyRegisterForm(POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(user.password)
            user.is_company = True
            user.save()
            CompanyProfile.objects.create(
                user=user,
                name=form.cleaned_data.get('name', ''),
                website=form.cleaned_data.get('website', ''),
                description=form.cleaned_data.get('description', ''),
            )
            user_created = _(
                'Company account has been created, please log in'
            )
            messages.success(request, user_created)
            del request.session['register_form_data']
            return redirect(reverse('users:login'))
        return redirect('users:c_register')

users/views/login.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View

from users.forms import LoginForm


class LoginView(View):
    template_name = 'users/pages/login.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect(reverse('base:home'))
        form = LoginForm()
        context = {
            'form': form,
            'form_action': reverse('users:login_create'),
        }
        return render(
            request, self.template_name, context=context)


class LoginCreateView(View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        form = LoginForm(request.POST)
        if form.is_valid():
            authenticated_user = authenticate(
                email=form.cleaned_data.get('email', ''),
                password=form.cleaned_data.get('password', ''),
            )
            if authenticated_user:
                messages.success(request, _('You are logged in'))
                login(request, authenticated_user)
            else:
                messages.error(request, _('Invalid email or password'))
                return redirect(reverse('users:login'))
        else:
            messages.error(request, _('Invalid credentials'))
            return redirect(reverse('users:login'))
        dashboard = (reverse('users:c_dashboard')
                     if authenticated_user.is_company
                     else reverse('users:u_dashboard'))
        return redirect(dashboard)

users/views/logout.py
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views import View


class UserLogoutView(LoginRequiredMixin, View):
    def get(self, request):
        raise Http404()

    def post(self, request):
        if request.POST.get('email') != request.user.email:
            messages.error(request, _('Invalid logout user'))
        else:
            logout(request)
            messages.success(request, _('Logged out successfully'))
        return redirect(reverse('users:login'))

users/templates/users/pages/applicant_dashboard.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Dashboard' %}{% endblock title %}

{% block content %}
    <div class="main-content dashboard center container article">
        {% include 'global/partials/messages.html' %}
        <div class="dashboard-tag center">
            <h2>{% translate 'Dashboard' %}</h2>
            <div class="applied-jobs applications center">
                {% if applications %}
                    <h2>{% translate 'Your Applicationss' %}</h2>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% translate 'ID' %}</th>
                                    <th>{% translate 'Job Title' %}</th>
                                    <th>{% translate 'Salary Expectation' %}</th>
                                    <th>{% translate 'Minimum Education' %}</th>
                                    <th>{% translate 'Previous Experience' %}</th>
                                    <th>{% translate 'Status' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for application in applications %}
                                    <tr>
                                        <td>#{{ application.id }}</td>
                                        <td>{{ application.job.title }}</td>
                                        <td>{{ application.salary_expectations }}</td>
                                        <td>{{ application.applicant_education }}</td>
                                        <td>{{ application.applicant_experiences }}</td>
                                        <td>
                                            {% if not application.job.is_finished %}
                                                {% translate "Ongoing..." %}
                                            {% else %}
                                                {% translate "Finished" %}
                                            {% endif %}
                                        </td>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3><p>{% translate 'You have no applications' %}</p></h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/pages/applicant_register.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Register' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="register-page">{% translate 'Applicant Register' %}</h2>
        {% include 'global/partials/messages.html' %}
        {% if not user.is_authenticated %}
            <div class="register-form-wrapper">
                {% include 'global/partials/form.html' %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

users/templates/users/pages/company_charts.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{% translate 'Charts' %}{% endblock title %}

{% block content %}
    <div class="main-content charts-main-container">
        {% include 'global/partials/messages.html' %}
        <div class="dashboard-tag center">
            <h2>{% translate 'Company Charts' %}</h2>
            <div class="company-charts">
                <div id="jobsChart"></div>
                <div id="applicationsChart"></div>
            </div>
        </div>
    </div>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script>
        const chartData1 = JSON.parse('{{ chart_data1|safe }}') || [];
        const dates1 = chartData1.map(item => new Date(item.created_date__date).toISOString());
        const jobCounts1 = chartData1.map(item => item.count);

        const data1 = [{
            x: dates1,
            y: jobCounts1,
            type: 'scatter',
            mode: 'lines+markers',
            line: { color: 'rgba(75, 192, 192, 1)' },
            marker: { color: 'rgba(75, 192, 192, 1)', size: 8 }
        }];

        const layout1 = {        
            title: '{% translate "Jobs Published" %}',
            xaxis: { title: '{% translate "Date" %}' },
            yaxis: { title: '{% translate "Count" %}' },
            margin: { l: 100, r: 100, t: 50 }
        };

        Plotly.newPlot('jobsChart', data1, layout1);

        const chartData2 = JSON.parse('{{ chart_data2|safe }}') || [];
        const dates2 = chartData2.map(item => new Date(item.applied_date__date).toISOString());
        const applicationCounts2 = chartData2.map(item => item.count);

        const data2 = [{
            x: dates2,
            y: applicationCounts2,
            type: 'scatter',
            mode: 'lines+markers',
            line: { color: 'rgba(75, 192, 192, 1)' },
            marker: { color: 'rgba(75, 192, 192, 1)', size: 8 }
        }];

        const layout2 = {
            title: '{% translate "Applications" %}',
            xaxis: { title: '{% translate "Date" %}' },
            yaxis: { title: '{% translate "Count" %}' },
            margin: { l: 100, r: 100, t: 50 }
        };

        Plotly.newPlot('applicationsChart', data2, layout2);
    </script>

    
{% endblock content %}

users/templates/users/pages/company_dashboard.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Dashboard' %}{% endblock title %}

{% block content %}
    <div class="main-content dashboard center container article">
        {% include 'global/partials/messages.html' %}
        <div class="dashboard-tag center">
            <h2>{% translate 'Company Dashboard' %}</h2>
            <div class="publish-job">
                <a href="{% url 'jobs:publish' %}">{% translate "Publish a new job" %}</a>
            </div>
            <div class="charts-button">
                <a href="{% url 'users:charts' %}">{% translate "Check the company charts" %}</a>
            </div>
            <div class="published-jobs center">
                {% if jobs %}
                    <h2>{% translate 'Your Published Jobs' %}</h2>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% translate 'ID' %}</th>
                                    <th>{% translate 'Job Title' %}</th>
                                    <th>{% translate 'Salary' %}</th>
                                    <th>{% translate 'Minimum Education' %}</th>
                                    <th>{% translate 'Skill Requirements' %}</th>
                                    <th>{% translate 'Applicants' %}</th>
                                    <th>{% translate 'Update Job Post' %}</th>
                                    <th>{% translate 'Publish Status' %}</th>
                                    <th>{% translate 'Delete Job Post' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for job in jobs %}
                                    <tr>
                                        <td>
                                            <a href="{% url 'jobs:update' job.id %}">#{{ job.id }}</a>
                                        </td>
                                        <td>{{ job.title }}</td>
                                        <td>{{ job.salary }}</td>
                                        <td>{{ job.minimum_education }}</td>
                                        <td>{{ job.skill_requirements }}</td>
                                        <td><a href="{% url 'jobs:applicants' job.id %}">{{ job.application_count }}</a></td>
                                        <td>
                                            {% if not job.is_finished %}
                                                <a href="{% url 'jobs:update' job.id %}">{% translate "Update" %}</a>
                                            {% else %}
                                                ➖
                                            {% endif %}
                                        </td>
                                        <td>
                                            {% if not job.is_finished %}
                                                ✔️
                                            {% else %}
                                                ✖️
                                            {% endif %}
                                        </td>
                                        <td>           
                                            <form class="inline-form form-delete" action="{% url 'users:job_delete' %}" method="POST">
                                                {% csrf_token %}
                                                <input type="hidden" name="id" value="{{ job.id }}">
                                                <button class="delete-button" type="submit">❌</button>
                                            </form>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3><p>{% translate 'You have no job posts published' %}</p></h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

users/templates/users/pages/company_register.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Register' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="register-page">{% translate 'Company Register' %}</h2>
        {% include 'global/partials/messages.html' %}
        {% if not user.is_authenticated %}
            <div class="register-form-wrapper">
                {% include 'global/partials/form.html' %}
            </div>
        {% endif %}
    </div>
{% endblock content %}

users/templates/users/pages/login.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Login' %}{% endblock title %}

{% block content %}
    <div class="main-content center container article">
        <h2 class="login-page">{% translate 'Login' %}</h2>
        {% include 'global/partials/messages.html' %}
        {% if not user.is_authenticated %}
            <div class="login-form-wrapper">
                {% include 'global/partials/form.html' %}
            </div>
        {% endif %}
    </div>
{% endblock content %}