base/urls.py
from django.urls import path

from base import views

app_name = 'base'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('register/', views.RegisterView.as_view(), name='register'),
]

jobs/urls.py
from django.urls import path

from jobs import views

app_name = 'jobs'

urlpatterns = [
    path('list/',
         views.JobListView.as_view(), name='list'),
    path('publish/',
         views.JobPublishView.as_view(), name='publish'),
    path('update/<int:pk>/',
         views.JobUpdateView.as_view(), name='update'),
    path('search/',
         views.JobListViewSearch.as_view(), name='search'),
    path('j/<int:pk>/',
         views.JobDetailView.as_view(), name='job'),
    path('a/<int:pk>/',
         views.JobApplyView.as_view(), name='apply'),
    path('applicants/<int:pk>/',
         views.JobApplicantsView.as_view(), name='applicants'),
]

jobs/models.py
from django.db import models

from users.models import ApplicantProfile, CompanyProfile
from utils import is_education_compatible, is_salary_compatible


class Job(models.Model):
    company_profile = models.ForeignKey(
        CompanyProfile, on_delete=models.CASCADE, related_name='jobs')
    title = models.CharField(max_length=100)
    salary = models.CharField(max_length=30)
    skill_requirements = models.TextField()
    minimum_education = models.CharField(max_length=40)
    hide_salary = models.BooleanField(default=False)
    is_finished = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)

    @property
    def company_name(self):
        return self.company_profile.name

    def __str__(self):
        return self.title


class Application(models.Model):
    job = models.ForeignKey(
        Job, on_delete=models.CASCADE, related_name='applications')
    applicant_profile = models.ForeignKey(
        ApplicantProfile,
        on_delete=models.CASCADE,
        related_name='applications')
    applicant_education = models.CharField(max_length=30)
    salary_expectations = models.CharField(max_length=30)
    applicant_experiences = models.TextField()
    compatibility = models.IntegerField()
    applied_date = models.DateTimeField(auto_now_add=True)

    @property
    def job_title(self):
        return self.job.title

    @property
    def applicant_name(self):
        return str(self.applicant_profile)

    @property
    def applicant_email(self):
        return str(self.applicant_profile.user)

    def save(self, *args, **kwargs):
        self.compatibility = self.calculate_compatibility()
        super().save(*args, **kwargs)

    def calculate_compatibility(self):
        score = 0
        if is_salary_compatible(self.salary_expectations, self.job.salary):
            score += 1
        if is_education_compatible(self.applicant_education,
                                   self.job.minimum_education):
            score += 1
        return score

    class Meta:
        unique_together = ['job', 'applicant_profile']

jobs/forms/application_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

from jobs.models import Application
from utils import MIN_EDUCATION_CHOICES, SALARY_CHOICES


class ApplicationForm(forms.ModelForm):
    salary_expectations = forms.ChoiceField(
        choices=SALARY_CHOICES,
        required=True,
        label=_('Salary Expectations *'),
    )
    applicant_education = forms.ChoiceField(
        choices=MIN_EDUCATION_CHOICES,
        required=True,
        label=_('Minimum Education *'),
    )
    applicant_experiences = forms.CharField(
        error_messages={
            'required': _('Experiences is required'),
        },
        required=True,
        widget=forms.Textarea,
        label=_('Your Experiences *'),
    )

    class Meta:
        model = Application
        fields = ['applicant_education', 'salary_expectations',
                  'applicant_experiences']

    def clean(self):
        cleaned_data = super().clean()
        job = cleaned_data.get('job')
        applicant_profile = cleaned_data.get('applicant_profile')
        if job and applicant_profile:
            existing_applications = Application.objects.filter(
                job=job, applicant_profile=applicant_profile)
            if existing_applications.exists():
                raise forms.ValidationError(
                    _('You have already applied to this job.'))
        return cleaned_data

jobs/forms/publish_form.py
from django import forms
from django.utils.translation import gettext_lazy as _

from jobs.models import Job
from utils import MIN_EDUCATION_CHOICES, SALARY_CHOICES


class PublishForm(forms.ModelForm):
    title = forms.CharField(
        error_messages={
            'required': _('Job title cannot be empty'),
        },
        required=True,
        label=_('Job Title *'),
    )
    salary = forms.ChoiceField(
        choices=SALARY_CHOICES,
        required=True,
        label=_('Salary *'),
    )
    minimum_education = forms.ChoiceField(
        choices=MIN_EDUCATION_CHOICES,
        required=True,
        label=_('Minimum Education *'),
    )
    skill_requirements = forms.CharField(
        error_messages={
            'required': _('Skill requirements is required'),
        },
        required=True,
        label=_('Skill Requirements *'),
        widget=forms.Textarea,
    )
    is_finished = forms.BooleanField(
        required=False,
        label=_('Mark job post as finished'),
    )

    class Meta:
        model = Job
        fields = ['title', 'salary', 'skill_requirements',
                  'minimum_education', 'hide_salary', 'is_finished']

jobs/views/applicants.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from jobs.models import Application, Job


class JobApplicantsView(LoginRequiredMixin, View):
    login_url = 'users:login'
    template_name = 'jobs/pages/applicants.html'
    redirect_field_name = 'next'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated and not request.user.is_company:
            return redirect('users:u_dashboard')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, pk):
        job = get_object_or_404(
            Job, id=pk, company_profile=request.user.companyprofile)
        applications = Application.objects.filter(job=job).order_by('id')

        sort_by_compatibility = request.GET.get('sort_by_compatibility')
        if sort_by_compatibility:
            applications = applications.order_by('-compatibility')

        context = {
            'job': job,
            'applications': applications,
            'sort_by_compatibility': sort_by_compatibility,
        }
        return render(request, self.template_name, context=context)

jobs/views/apply.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from jobs.forms import ApplicationForm
from jobs.models import Application, Job


class JobApplyView(LoginRequiredMixin, View):
    login_url = 'users:login'
    template_name = 'jobs/pages/apply.html'
    redirect_field_name = 'next'

    def get(self, request, pk):
        if request.user.is_company:
            raise Http404()
        job = get_object_or_404(Job, pk=pk)
        if job.is_finished:
            raise Http404()
        applicant_profile = request.user.applicantprofile
        context = {
            'job': job,
        }
        if Application.objects.filter(
                job=job, applicant_profile=applicant_profile).exists():
            context['already_applied'] = True
        else:
            context['form'] = ApplicationForm()
        return render(
            self.request,
            self.template_name,
            context
        )

    def post(self, request, pk):
        if request.user.is_company:
            raise Http404()
        job = get_object_or_404(Job, pk=pk)
        if job.is_finished:
            raise Http404()
        form = ApplicationForm(request.POST)
        if form.is_valid():
            application = form.save(commit=False)
            application.job = job
            application.applicant_profile = request.user.applicantprofile
            application.save()
            messages.success(
                request,
                _('Application submitted successfully, '
                  'you will be contacted via email or phone call shortly '
                  'with the feedback'))
            return redirect(reverse('users:u_dashboard'))
        messages.error(request, _('Failed to submit application'))
        context = {
            'form': form,
            'job': job,
        }
        return render(self.request, self.template_name, context)

jobs/views/publish.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views import View

from jobs.forms import PublishForm


class JobPublishView(LoginRequiredMixin, View):
    login_url = 'users:login'
    template_name = 'jobs/pages/publish.html'
    redirect_field_name = 'next'

    def get(self, request):
        if not request.user.is_company:
            raise Http404()
        form = PublishForm()
        context = {
            'form': form,
        }
        return render(
            self.request,
            self.template_name,
            context
        )

    def post(self, request):
        if not request.user.is_company:
            raise Http404()
        form = PublishForm(request.POST)
        if form.is_valid():
            job = form.save(commit=False)
            job.company_profile = request.user.companyprofile
            job.save()
            messages.success(request, _('Job published successfully'))
            return redirect(reverse('users:c_dashboard'))
        messages.error(request, _('Failed to publish job'))
        return render(self.request, self.template_name)

jobs/views/search.py
from django.db.models import Count, Q
from django.http import Http404
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, ListView

from jobs.models import Job


class JobListView(ListView):
    model = Job
    context_object_name = 'jobs'
    paginate_by = None
    ordering = ['-id']
    template_name = 'jobs/pages/list.html'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(is_finished=False)
        queryset = queryset.select_related('company_profile')
        queryset = queryset.annotate(application_count=Count('applications'))
        return queryset


class JobListViewSearch(JobListView):
    template_name = 'jobs/pages/list.html'

    def get_queryset(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '').strip()
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(
            Q(title__icontains=search_term),
            is_finished=False,
        ).order_by('-id')
        return queryset

    def get_context_data(self, *args, **kwargs):
        search_term = self.request.GET.get('q', '').strip()
        queryset = self.get_queryset(*args, **kwargs)

        if search_term:
            queryset = queryset.filter(Q(title__icontains=search_term))

        ctx = super().get_context_data(*args, **kwargs)
        search_translation = _('Searching for')

        ctx.update({
            'page_title': f'{search_translation} "{search_term}"',
            'search_term': search_term,
            'additional_url_query': f'&q={search_term}',
            'jobs': queryset,
        })
        return ctx


class JobDetailView(DetailView):
    model = Job
    context_object_name = 'job'
    template_name = 'jobs/pages/detail.html'

    def get_context_data(self, *args, **kwargs):
        ctx = super().get_context_data(*args, **kwargs)
        ctx.update({
            'is_detail_page': True
        })
        return ctx

    def get_queryset(self, *args, **kwargs):
        qs = super().get_queryset(*args, **kwargs)
        qs = qs.filter(is_finished=False)
        if not qs:
            raise Http404()
        return qs

jobs/views/update.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import redirect, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.utils.translation import gettext as _
from django.views import View

from jobs.forms import PublishForm
from jobs.models import Job


@method_decorator(
    login_required(login_url='users:login', redirect_field_name='next'),
    name='dispatch'
)
class JobUpdateView(View):
    template_name = 'jobs/pages/update.html'

    def get(self, request, pk):
        try:
            job = Job.objects.get(
                id=pk, company_profile__user=request.user)
        except Job.DoesNotExist:
            raise Http404()
        form = PublishForm(instance=job)
        context = {
            'form': form,
            'job': job,
        }
        return render(self.request, self.template_name, context)

    def post(self, request, pk):
        try:
            job = Job.objects.get(
                id=pk, company_profile__user=request.user)
        except Job.DoesNotExist:
            raise Http404()
        form = PublishForm(request.POST, instance=job)
        if form.is_valid():
            form.save()
            messages.success(request, _('Job updated successfully'))
            return redirect(reverse('users:c_dashboard'))
        messages.error(request, _('Failed to update job'))
        context = {
            'form': form,
            'job': job,
        }
        return render(self.request, self.template_name, context)

jobs/templates/jobs/pages/applicants.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Applicants for ' %}{{ job }}{% endblock title %}

{% block content %}
    <div class="main-content dashboard center container article">
        {% include 'global/partials/messages.html' %}
        <div class="dashboard-tag center">
            <h2>{% translate 'Applicants for ' %}{{ job }}</h2>
            <div class="applicants-jobs center">
                {% if applications %}
                    <div class="sort-container">
                        <h3>
                            {% if not sort_by_compatibility %}
                                <h2>{% translate 'Sorting by order of application' %}</h2>
                                <div class="sort-apps">
                                    <a href="{% url 'jobs:applicants' job.id %}?sort_by_compatibility=true">
                                        {% trans "Sort by compatibility with the Job" %}
                                    </a>
                                </div>
                            {% else %}
                                <h2>{% translate 'Sorting by best candidates for this job' %}</h2>
                                <div class="sort-apps">
                                    <a href="{% url 'jobs:applicants' job.id %}">
                                       {% trans "Sort by order of application" %}
                                    </a>
                                </div>
                            {% endif %}
                        </h3>
                    </div>
                    <div class="table-wrapper">
                        <table>
                            <thead>
                                <tr>
                                    <th>{% translate 'ID' %}</th>
                                    <th>{% translate 'Applicant Full Name' %}</th>
                                    <th>{% translate 'Applicant Email' %}</th>
                                    <th>{% translate 'Applicant Phone Number' %}</th>
                                    <th>{% translate 'Salary Expectation' %}</th>
                                    <th>{% translate 'Education' %}</th>
                                    <th>{% translate 'Experiences' %}</th>
                                    <th>{% translate 'Years of Experience' %}</th>
                                    <th>{% translate 'Skills' %}</th>
                                    <th>{% translate 'Compatibility with the Job' %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for application in applications %}
                                    <tr>
                                        <td>#{{ application.id }}</td>
                                        <td>{{ application.applicant_profile }}</td>
                                        <td>{{ application.applicant_profile.user }}</td>
                                        <td>{{ application.applicant_profile.user.phone_number }}</td>
                                        <td>{{ application.salary_expectations }}</td>
                                        <td>{{ application.applicant_education }}</td>
                                        <td>{{ application.applicant_experiences }}</td>
                                        <td>{{ application.applicant_profile.years_experience }}</td>
                                        <td>{{ application.applicant_profile.skills }}</td>
                                        <td>
                                            {% if application.compatibility == 2 %}
                                                ➕➕
                                            {% elif application.compatibility == 1 %}
                                                ➕
                                            {% else %}
                                                ➖
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                {% else %}
                    <h3><p>{% translate 'No applications found for this job' %}</p></h3>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/pages/apply.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Job Application' %}{% endblock title %}

{% block content %}
    <div class="main-content publish center container article">
        <div class="publish-container">
            <div class="publish-form">
                {% include 'global/partials/messages.html' %}
                <h2>{% translate 'Job Application' %}</h2>
                {% if user.is_authenticated %}
                    {% if already_applied %}
                        <h3>{% translate 'You have already applied to this job!' %}</h3>
                    {% else %}
                        {% include 'global/partials/form.html' %}
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/pages/detail.html
{% extends 'global/base.html' %}
{% load i18n %}

{% block title %}{{ job.title }}{% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        <div class="job-item-details job-details">
            <div class="job-title-container">
                <h2 class="job-title">
                    {{ job.title }}
                </h2>
            </div>
            <div class="job-author">
                <h4>{% translate "Company - " %}{{ job.company_name }}</h4>
            </div>
            <div class="job-meta-container">
                <div class="job-skill-requirements">
                    <h4><p>{% translate "Skill Requirements - " %}{{ job.skill_requirements }}</p></h4>
                </div>
                <div class="job-minimum-education">
                    <h4><p>{% translate "Minimum Education - " %}{{ job.minimum_education }}</p></h4>
                </div>
                <div class="job-salary">
                    {% if job.hide_salary %}
                    <h4><p>{% translate "Salary - " %}{{ job.salary }}</p></h4>
                    {% endif %}
                </div>
            </div>
            <div class="apply-job">
                {% if not user.is_company %}
                        <a href="{% url 'jobs:apply' job.id %}">{% translate "Apply for this job" %}</a>
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/pages/list.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}
    {% if search_term and page_title %}
        {{ page_title }}
    {% else %}
        {% translate 'Jobs List' %}
    {% endif %}
{% endblock title %}

{% block content %}
    <div class="main-content center container article search-main-container jobs-main-container">
        {% include 'global/partials/messages.html' %}
        <div class="jobs-search-tag center">
            <h2>{% translate 'Jobs List' %}</h2>
        </div>
        <div class="search-container">
            <div class="container">
                <form action="{% url 'jobs:search' %}" method="GET" class="search-form">
                    <input 
                        type="search" class="search-input" 
                        name="q" value="{{ search_term }}" required
                        placeholder="{% translate 'Search for a job post' %}">
                    <button type="submit" class="search-button"><i class="fas fa-search"></i> </button>
                </form>
            </div>
        </div>
        <div class="job-list">
            {% if jobs %}
                <div class="table-wrapper">
                    <table>
                        <thead>
                            <tr>
                                <th>{% translate 'Job Title' %}</th>
                                <th>{% translate 'Company' %}</th>
                                <th>{% translate 'Salary' %}</th>
                                <th>{% translate 'Minimum Education' %}</th>
                                <th>{% translate 'Applicants' %}</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for job in jobs %}
                                <tr>
                                    <td><a href="{% url 'jobs:job' job.id %}">{{ job.title }}</a></td>
                                    <td>{{ job.company_name }}</td>
                                    <td>
                                        {% if job.hide_salary %}
                                            ➖
                                        {% else %}
                                            {{ job.salary }}
                                        {% endif %}
                                    </td>
                                    <td>{{ job.minimum_education }}</td>
                                    <td>{{ job.application_count }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            {% else %}
                <h3><p>{% translate 'No jobs found' %}</p></h3>
            {% endif %}
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/pages/publish.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Publish Job' %}{% endblock title %}

{% block content %}
    <div class="main-content publish center container article">
        <div class="publish-container">
            <div class="publish-form">
                {% include 'global/partials/messages.html' %}
                <h2>{% translate 'Publish New Job' %}</h2>
                {% if user.is_authenticated %}
                    {% include 'global/partials/form.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}

jobs/templates/jobs/pages/update.html
{% extends 'global/base.html' %}
{% load i18n %}
{% block title %}{% translate 'Update Job' %}{% endblock title %}

{% block content %}
    <div class="main-content publish center container article">
        <div class="publish-container">
            <div class="publish-form">
                {% include 'global/partials/messages.html' %}
                <h2>{% translate 'Update Job Post' %}</h2>
                {% if user.is_authenticated %}
                    {% include 'global/partials/form.html' %}
                {% endif %}
            </div>
        </div>
    </div>
{% endblock content %}